wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 256
epochs:
  value: 500
layers:
  value:
  - 17
  - 8
  - 17
  - 18
loss:
  value: mae
lr:
  value: 0.01
optimizer:
  value: mini_bgd
