wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 128
epochs:
  value: 100
layers:
  value:
  - 64
  - 16
  - 6
lr:
  value: 0.001
optimizer:
  value: mini_bgd
thresh:
  value: 0.7
