wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 1000
layers:
  value:
  - 64
  - 16
  - 1
loss:
  value: cross_entropy
lr:
  value: 0.0001
optimizer:
  value: bgd
