wandb_version: 1

activations:
  value: relu
batch_size:
  value: 32
epochs:
  value: 1000
layers:
  value:
  - 64
  - 32
  - 1
loss:
  value: cross_entropy
lr:
  value: 0.1
optimizer:
  value: mini_bgd
