wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 1000
layers:
  value:
  - 64
  - 32
  - 16
  - 8
lr:
  value: 0.1
optimizer:
  value: bgd
thresh:
  value: 0.3
