wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 256
epochs:
  value: 100
layers:
  value:
  - 64
  - 32
  - 16
  - 8
lr:
  value: 0.01
optimizer:
  value: mini_bgd
thresh:
  value: 0.3
