wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 500
layers:
  value:
  - 64
  - 32
  - 16
  - 8
lr:
  value: 0.001
optimizer:
  value: mini_bgd
thresh:
  value: 0.9
