wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 256
epochs:
  value: 50
layers:
  value:
  - 16
  - 8
  - 1
loss:
  value: cross_entropy
lr:
  value: 0.01
optimizer:
  value: bgd
