_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 17
                - 23
                - 55
            "4": 3.11.4
            "5": 0.18.3
            "8":
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
activations:
    value: sigmoid
batch_size:
    value: 256
epochs:
    value: 500
layers:
    value:
        - 64
        - 16
        - 8
lr:
    value: 0.001
optimizer:
    value: sgd
thresh:
    value: 0.5
